### ISSUE TITLE
wxGlade does not preserve window layout after every second restart

### ISSUE THREAD

**Issue by amstelchen** [wxGlade/wxGlade#514] opened 2022-04-18 15:56 UTC
When I start **wxGlade** consecutively, one out of two times the main window is opened in full size, the other time it is opened in half size.

> $ python ~/Repositories/wxGlade/wxglade.py &
> $ cat ~/.wxglade/wxgladerc
```
...
widths_l0 = 800
...
```

> $ python ~/Repositories/wxGlade/wxglade.py &
Then after maximising the window:
```
...
widths_l0 = 1920
...
```
Then, after a consecutive start, `widths_l0 = 800` again.

Nothing suspicious in _~/.wxglade/wxglade.log_.

Could you please check what is going on? Thanks.

> INFO    : Starting wxGlade version "1.1.0pre" on Python 3.10.4
> INFO    : Using wxPython 4.1.1
> 
> yay -Q wxgtk3
> wxgtk3 3.0.5.1-3
> pip show wxpython
> Version: 4.1.1
> pip show wxglade
> Version: 1.1.0rc0
>

**Comment by DietmarSchwertberger** [comment] 2022-04-18 17:01
I will look into this in the next days.

**Comment by DietmarSchwertberger** [comment] 2022-04-21 18:59
I see some issues with sizing the frame that I don't see on Windows.
When I set the size, I later on receive a second size event with a larger size. I need to check whether this is a general bug or wxGlade specific.

**Comment by DietmarSchwertberger** [comment] 2022-04-21 20:23
Could you please try adding some lines after `self.Show()` in `main.py`, `wxGladeFrame.__init__`?
(around line 424)
```
        self.Show()

        w, h = self.GetSize()
        if w>size[0] or h>size[1]:
            # can happen on e.g. Linux due to menu/tool/status bar
            new_size = ( 2*size[0] - w, 2*size[1] - h )
            self.SetSize(new_size)
```

**Comment by amstelchen** [comment] 2022-04-22 16:59
No change.

`self.GetSize()` results in `(800, 1051)` and `size[0]` has 800, `size[1]` has 1051 set in `init_layout_settings()`, the window does the same every second time still.

I tend to set width manually to 1920 pixels in `init_layout_settings()` but I suppose that's a dirty workaround.

**Comment by DietmarSchwertberger** [comment] 2022-04-23 13:53
Unfortunately I can't debug this as I can't reproduce.
What platform is this?

You may add a handler for `EVT_SIZE` at the end of `wxGladeFrame.__init__` and set a breakpoint to see why this happens:

```
        self.Bind(wx.EVT_SIZE, self.on_size)

    def on_size(self, event):
        print("on_size", self.Size)
        event.Skip()
```

**Comment by DietmarSchwertberger** [comment] 2022-08-02 19:53
The resizing bug with some Linux is fixed in master branch. 
The original bug I can't reproduce. I'm closing this until I get further input.

**Closed by DietmarSchwertberger** 2022-08-02 19:53 UTC
Labels: bug
