### ISSUE TITLE
module 'time' has no attribute 'clock' when importing .xrc file

### ISSUE THREAD

**Issue by jmartens** [wxGlade/wxGlade#499] opened 2021-11-01 14:45 UTC
When trying to import [dicomgui.xrc](https://github.com/bastula/dicompyler/blob/3075b9fcb45f729ebd791ae2ab09bc410af85bf7/dicompyler/resources/dicomgui.xrc) I get the following error:

```
WARNING : Unknown widget "wxStdDialogButtonSizer" - fallback to generic widget "CustomWidget"
WARNING : Unknown widget "button" - fallback to generic widget "CustomWidget"
WARNING : Unknown widget "button" - fallback to generic widget "CustomWidget"
ERROR   : An internal error occurred while Import File "b'dicomgui.xrc'"
An unexpected error occurred!

Exception type:      <class 'AttributeError'>
Exception details:   module 'time' has no attribute 'clock'

Application stack traceback:
  File "/usr/share/wxglade/main.py", line 1159, in import_xrc
    self._open_app(ibuffer)
  File "/usr/share/wxglade/main.py", line 907, in _open_app
    start = time.clock()

Date and time:       2021-11-01T15:42:47.929898
Python version:      3.8.10
wxPython version:    4.0.7
wxWidgets platform:  __WXGTK__
wxGlade version:     0.9.4
```

**Comment by jmartens** [comment] 2021-11-01 14:52
It seems Ubuntu provides a not so recent version of WxGlade: 0.9.4

**Comment by DietmarSchwertberger** [comment] 2021-11-01 16:51
Duplicate of #387

Please use a more recent version of wxGlade. You don't need a package or installer. Just clone the repository or download a release and the run wxglade.py

**Closed by DietmarSchwertberger** 2021-11-01 16:51 UTC
Labels: duplicate
