### ISSUE TITLE
Error occurs when adding a widget

### ISSUE THREAD

**Issue by avriessen** [wxGlade/wxGlade#506] opened 2022-01-08 12:17 UTC
When I add a frame or want to see a preview an error occurs (See below).
All I have to do to get this is to start wxGlade and add a frame to the application which will show the error below.
After this clicking on a widget is enough to get the error again, except when clicking on a sizer.

ERROR   : None
An unexpected error occurred!

Exception type:      <class 'TypeError'>
Exception details:   Sizer.SetItemMinSize(): arguments did not match any overloaded call:
  overload 1: argument 3 has unexpected type 'float'
  overload 2: argument 2 has unexpected type 'int'
  overload 3: argument 1 has unexpected type 'ExpandoTextCtrl'
  overload 4: argument 1 has unexpected type 'ExpandoTextCtrl'
  overload 5: argument 1 has unexpected type 'ExpandoTextCtrl'
  overload 6: argument 1 has unexpected type 'ExpandoTextCtrl'

Application stack traceback:
  File "/usr/lib64/python3.10/site-packages/wx/core.py", line 2254, in Notify
    self.notify()
  File "/usr/lib64/python3.10/site-packages/wx/core.py", line 3410, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/site-packages/wxglade/main.py", line 136, in edit_properties
    self.create_editor(edit_widget)
  File "/usr/lib/python3.10/site-packages/wxglade/main.py", line 196, in create_editor
    property_instance.create_editor(current_page, current_sizer)
  File "/usr/lib/python3.10/site-packages/wxglade/new_properties.py", line 1390, in create_editor
    hsizer.SetItemMinSize(self.text, 100, h * 1.5)

Date and time:       2022-01-08T12:04:35.030025
Python version:      3.10.1
wxPython version:    4.0.7
wxWidgets platform:  __WXGTK__
wxGlade version:     1.0.3

**Comment by DietmarSchwertberger** [comment] 2022-01-08 12:30
Please try wxGlade 1.0.4. This is caused by a change in Python 3.10.
(Duplicate of issue #504.)

**Closed by DietmarSchwertberger** 2022-01-08 12:30 UTC
Labels: bug, duplicate, Python3.10
