### ISSUE TITLE
moving a button to a different notebook page crashed.

### ISSUE THREAD

**Issue by hcoin** [wxGlade/wxGlade#364] opened 2019-05-07 20:09 UTC
Reporting as asked.  Setup:  Top frame with one sizer holding one notebook.  First page has a sizer, second has a sizer with a list control and a button.  Crash occured when attempting to drag the botton from the page with the list control to the empty sizer.

ERROR   : None
An unexpected error occurred!

Exception type:      <class 'RuntimeError'>
Exception details:   wrapped C/C++ object of type Panel has been deleted

Application stack traceback:
  File "/usr/share/wxglade/tree.py", line 756, in on_change_selection
    misc.set_focused_widget(widget)
  File "/usr/share/wxglade/misc.py", line 39, in set_focused_widget
    widget.update_view(selected=True)
  File "/usr/share/wxglade/edit_windows.py", line 651, in update_view
    if self.sel_marker: self.sel_marker.Show(selected)
  File "/usr/share/wxglade/misc.py", line 148, in Show
    self.tags = [SelectionTag(self.parent) for i in range(4)]
  File "/usr/share/wxglade/misc.py", line 148, in <listcomp>
    self.tags = [SelectionTag(self.parent) for i in range(4)]
  File "/usr/share/wxglade/misc.py", line 108, in __init__
    wx.Window.__init__(self, parent, wx.ID_ANY, **kwds)

Date and time:       2019-05-07T15:05:35.935814
Python version:      3.7.3
wxPython version:    4.0.4
wxWidgets platform:  __WXGTK__
wxGlade version:     0.8.3

**Comment by DietmarSchwertberger** [comment] 2019-05-08 20:02
Is this reproducible for you?
I could not reproduce this on my setups, but they are not 100% identical to yours.

If it's reproducible, could you please try with a line `if not self.parent: return` added?


File `misc.py:`
```
class SelectionMarker(object):
    ...
    def Show(self, visible):
        if self.visible != visible:
            self.visible = visible
            if self.visible:
                if not self.parent: return
                if not self.tags:
                    self.tags = [SelectionTag(self.parent) for i in range(4)]
                for i,pos in enumerate(self.tag_pos):
                    self.tags[i].SetPosition(pos)
                    self.tags[i].Show()
            else:
                for tag in self.tags:
                    tag.Destroy()
                self.tags = None
```

**Comment by DietmarSchwertberger** [comment] 2019-05-26 18:30
The potential workaround will be in the next release.

**Closed by DietmarSchwertberger** 2019-05-26 18:30 UTC
Labels: bug
