### ISSUE TITLE
TextCtrl changes size in Design window when a border or alignment is set.

### ISSUE THREAD

**Issue by reticulatus** [wxGlade/wxGlade#536] opened 2023-12-05 10:31 UTC
OS: Linux Mint 21.2
wxPython: wxPython 4.2.1 gtk3 (phoenix) wxWidgets 3.2.2.1
Python: 3.10.12
wxGlade: 1.0.5 and 1.1.0a2

If I add a TextCtrl to a BoxSizer or a FlexGridSizer and then check one of the Border options or one of the Alignment options (excluding wxEXPAND) in the TextCtrl's Layout tab, the TextCtrl increases in size in the Design window. If I save the .wxg file and then re-open it, the size of the TextCtrl reverts to its original default size.

**Simple example:**

* Start wxGlade.
* Add a Frame.
* Add a TextCtrl to the BoxSizer's SLOT 0.
* In the TextCtrl's Common tab, its Size is showing as 89,28 (on my system).
* In the TextCtrl's Layout tab, do not change the Proportion setting or check the wxEXPAND option, but check one of the Border options.
* The size of the TextCtrl in the Design window increases.
* In the TextCtrl's Common tab, its Size is now showing as 93,40.
* If I keep clicking the Border SpinCtrl's '+' button, the height of the TextCtrl keeps increasing until the setting reaches 5, after which it doesn't increase any further.
* Do not check the Size option, but save the project to a .wxg file.
* Re-open the .wxg file.
* The TextCtrl has reverted to its original default size in the Design window and in the Size setting in its Common tab.

If I repeat the above steps but check wxALIGN_RIGHT instead of checking one of the Border options, then the TextCtrl's size gets set to 93,49.

Unchecking the Border or Alignment option can cause the TextCtrl's height increase further.

I have also noticed that if I check the Size option of a TextCtrl and explicitly set it to a value such as 100,-1 then the size displayed in the Design window still increases, although it is still showing as 100,-1 in the Common tab.

Other composite controls that contain a TextCtrl, such as ComboBox, SpinCtrl and DatePickerCtrl do not display the same issue.

I first noticed this issue when I was placing TextCtrls in a FlexGridSizer and was trying to set all the controls in a row to wxALIGN_CENTER_VERTICAL to line them up in particular way. Because the TextCtrls kept changing size, I had to keep saving and loading the project to see if the controls were lined up correctly.

**Comment by reticulatus** [comment] 2023-12-05 16:57
The size in the preview window never changes, only the design window. That is one workaround that I have used, i.e. keep pressing F5 to refresh the preview window to see how the layout really looks. However, when working on a large design it becomes a bit clumsy when the design and preview windows keep obstructing each other.

**Comment by reticulatus** [comment] 2023-12-05 17:00
![Screenshot at 2023-12-05 16-58-34](https://github.com/wxGlade/wxGlade/assets/6072789/6bb7439f-1307-45a0-8f95-6206ff818178)

**Comment by DietmarSchwertberger** [comment] 2023-12-05 17:36
OK, thanks, I will check in my Linux VM.

**Comment by DietmarSchwertberger** [comment] 2023-12-05 19:20
I can see it on Linux with 4.2.1. It was OK with 4.1.x.
On Windows both versions are OK (only a small increase in width). I will try to find the cause.

**Comment by DietmarSchwertberger** [comment] 2023-12-10 22:47
Between these releases there were some changes in the TextCtrl code for gtk. That makes it harder for me to debug. I prefer Windows problems...

**Comment by DietmarSchwertberger** [comment] 2023-12-18 21:23
Building wxPython on Linux is still a nightmare.
Anyway, I could build it on one of my Ubuntu installations.
This should be fixed in the next wxPython release.

The root cause is this line in wxWidgets [src/gtk/textctrl.cpp]:
`tsize.IncBy( GTKGetEntryMargins(GetEntry()) );`

The relevant code in the wxWidgets versions:

wxWidgets 3.1.0
```
 wxSize wxTextCtrl::DoGetSizeFromTextSize(int xlen, int ylen) const
{
    wxASSERT_MSG( m_widget, wxS("GetSizeFromTextSize called before creation") );

    wxSize tsize(xlen, 0);
    int cHeight = GetCharHeight();

    if ( IsSingleLine() )
    {
        if ( HasFlag(wxBORDER_NONE) ) {
            tsize.y = cHeight;
            tsize.IncBy(9, 0);
        } else {
            // default height
            tsize.y = GTKGetPreferredSize(m_widget).y;
            // Add the margins we have previously set, but only the horizontal border
            // as vertical one has been taken account at GTKGetPreferredSize().
            // Also get other GTK+ margins.
            tsize.IncBy( GTKGetEntryMargins(GetEntry()).x, 0);
        }
    }

    //multiline
    else {  }

    // Perhaps the user wants something different from CharHeight, or ylen is used as the height of a multiline text.
    if ( ylen > 0 )  tsize.IncBy(0, ylen - cHeight);

    return tsize;
}
```

wxWidgets 3.2.1:
```
 wxSize wxTextCtrl::DoGetSizeFromTextSize(int xlen, int ylen) const
{
    wxASSERT_MSG( m_widget, wxS("GetSizeFromTextSize called before creation") );

    int cHeight = GetCharHeight();
    wxSize tsize(xlen, cHeight);

    if ( IsSingleLine() ) {
        if ( HasFlag(wxBORDER_NONE) ) {
            tsize.IncBy(9, 0);
        } else {
            // default height
            tsize.y = GTKGetPreferredSize(m_widget).y;
            // Add the margins we have previously set.
            tsize.IncBy( GTKGetEntryMargins(GetEntry()) );
        }
    }
    //multiline
    else {  }

    // We should always use at least the specified height if it's valid.
    if ( ylen > tsize.y )  tsize.y = ylen;

    return tsize;
}
```

current
```
wxSize wxTextCtrl::DoGetSizeFromTextSize(int xlen, int ylen) const
{
    wxASSERT_MSG( m_widget, wxS("GetSizeFromTextSize called before creation") );

    int cHeight = GetCharHeight();
    wxSize tsize(xlen, cHeight);

    if ( IsSingleLine() )
    {
        // Default height
        tsize.y = GTKGetPreferredSize(m_widget).y;
        // Add padding + border size
        tsize.x += GTKGetEntryMargins(GetEntry()).x;
    }
    //multiline
    else {  }

    // We should always use at least the specified height if it's valid.
    if ( ylen > tsize.y )  tsize.y = ylen;

    return tsize;
}
```

**Comment by DietmarSchwertberger** [comment] 2023-12-18 21:41
I don't see how to call GTKGetEntryMargins or GTKGetPreferredSize from Python. So I can't replace this code with some Python code as workaround.

The only workaround I'm seeing is this one in edit_sizers/edit_sizers.py:

![grafik](https://github.com/wxGlade/wxGlade/assets/5512021/7a6413bf-f6fe-4500-8c4b-c801463bc24f)

The comment is out of date, as wxGlade does now re-create TextCtrl on style change. Still, I would like to leave the SetSize() call there.

**Comment by DietmarSchwertberger** [comment] 2023-12-20 20:19
Could you please test this workaround whether it's working for you?
Then I would include it into rev. 1.1.

**Comment by reticulatus** [comment] 2023-12-20 21:19
I edited edit_sizers.py as shown the png of the diff you posted.

I then tested the following cases starting from a fresh design in each case:

1. If I check the TextCtrl's wxRIGHT option, the TextCtrl no longer immediately changes size.
However, if I then click the '+' button on the Border SpinCtrl, the TextCtrl's height does increase in the Design window.

2. If I check the TextCtrl's wxALIGN_CENTER_HORIZONTAL it moves to the correct position and doesn't change size.
However, if I then uncheck that option, the TextCtrl moves back to the left of the Frame and does increase in size.

3. If I check the TextCtrl's Size option on its Common tab and set the size to 100,-1 then the TextCtrl's height jumps to a larger value, although the size setting still shows 100,-1.

It looks like the code change only prevents the resizing for the first action in setting a border or alignment. However, the resizing is still happening for the other changes.

**Comment by DietmarSchwertberger** [comment] 2023-12-22 21:10
OK, next try. I have created a separate branch ISSUE_536 for this.
Please test. For me it seems to work.

**Comment by reticulatus** [comment] 2023-12-22 21:42
I have tested the code from the ISSUE_536 branch and the workaround is working for me also.

Thank you for investigating this problem and devising the workaround.

**Comment by DietmarSchwertberger** [comment] 2023-12-23 18:25
When you open this .wxg file, can you navigate in the Design window using the arrow keys?
On my Linux installations I can navigate in the Tree window, but not in the Design window when something was opened or pasted.
The workaround is to call SetFocus on one of the widgets. I need to figure out the best way of doing this. After that I will prepare 1.1.0a3.

**Comment by reticulatus** [comment] 2023-12-23 18:32
> When you open this .wxg file, can you navigate in the Design window using the arrow keys? On my Linux installations I can navigate in the Tree window, but not in the Design window when something was opened or pasted. The workaround is to call SetFocus on one of the widgets. I need to figure out the best way of doing this. After that I will prepare 1.1.0a3.

Which .wxg file do you mean?

**Comment by DietmarSchwertberger** [comment] 2023-12-23 18:41
The one from your screenshot above. Frame -> Panel -> Sizer -> TextCtrl

**Comment by reticulatus** [comment] 2023-12-23 18:54
I get the same. The arrow keys navigate in the Tree window, but not in the Design window.

**Comment by DietmarSchwertberger** [comment] 2023-12-23 18:58
OK. This is not critical, but anyway I will look for a solution.
One other thing I'm seeing sometimes is that wxGlade does not react to mouse clicks any more. Setting focus or resizing windows is still working and when I want to close the window I get the dialog about unsaved changes, but other than that I can't do anything. That's weird and it's difficult to debug...

**Comment by DietmarSchwertberger** [comment] 2024-05-18 18:00
The repository now has  a workaround to call wx.Yield before a TextCtrl or ComboBox is created.
This seems to avoid the issue where key events are not handled and also where a drag event does not return, resulting in a hanging program.
I don't know, but I would guess that there is some strange bug in gtk or wx for gtk.

Another thing that does not seem to work on Linux is the dynamic toolbar. wxGlade dynamically enables and disables e.g. the tool buttons for Undo/Re-Do, but on gtk it seems that this can only be done once and will not have an effect later on (and also ToolBar.Realize needs to be called). I don't see a workaround other than completely re-creating the toolbar again and again, but that's something I don't want to do. As of now, the toolbar is just there to display the associated shortcut keys.

The remaining issue to be looked at is the focus handling. After that and some documentation update 1.1 should be ready.

**Comment by reticulatus** [comment] 2024-05-18 18:19
I just downloaded the latest master branch.

When I run it and add a Frame, as soon as I add a TextCtrl, wxGlade crashes with the following error:

```
ERROR   : None
An unexpected error occurred!

Exception type:      <class 'AttributeError'>
Exception details:   module 'compat' has no attribute 'IS_GTK'

Application stack traceback:
  File "/home/richardt/Sources/applications/UI Builders/wxGlade/1.1.0/2024-05-18/wxGlade-master/edit_base.py", line 810, in on_drop_widget
    new_widget = common.widgets[common.widget_to_add](self.parent, self.index)
  File "/home/richardt/Sources/applications/UI Builders/wxGlade/1.1.0/2024-05-18/wxGlade-master/widgets/text_ctrl/text_ctrl.py", line 58, in builder
    if parent.widget: editor.create()
  File "/home/richardt/Sources/applications/UI Builders/wxGlade/1.1.0/2024-05-18/wxGlade-master/edit_base.py", line 308, in create
    self.recursive_create_widgets(level=0)
  File "/home/richardt/Sources/applications/UI Builders/wxGlade/1.1.0/2024-05-18/wxGlade-master/edit_base.py", line 312, in recursive_create_widgets
    self.create_widget()
  File "/home/richardt/Sources/applications/UI Builders/wxGlade/1.1.0/2024-05-18/wxGlade-master/widgets/text_ctrl/text_ctrl.py", line 40, in create_widget
    if compat.IS_GTK: wx.Yield()  # avoid problems where the widget is consuming all events

Date and time:       2024-05-18T19:16:51.987112
Python version:      3.10.12
wxPython version:    4.2.1
wxWidgets platform:  __WXGTK__
wxGlade version:     1.1.0a2
```

**Comment by DietmarSchwertberger** [comment] 2024-05-19 08:28
Sorry, thought I had uploaded IS_GTK already. Now it should work.

**Comment by reticulatus** [comment] 2024-05-19 09:47
I re-tested, adding TextCtrl and ComboBox and it no longer crashes.

**Comment by DietmarSchwertberger** [comment] 2024-07-07 17:59
version 1.1.0b1 is online

**Comment by DietmarSchwertberger** [comment] 2024-07-07 18:00
The focus handling should be slightly better with the recent beta release.

**Closed by DietmarSchwertberger** 2024-07-07 17:59 UTC
Labels: bug, wxWidgets
