### ISSUE TITLE
Bug on previewing dialog 2nd time round 

### ISSUE THREAD

**Issue by johns1c** [wxGlade/wxGlade#491] opened 2021-06-17 13:13 UTC
Recently been getting an error when hitting F5 or choosing menu option preview when already or has been displayed.  Object is a dialog at the top level with a cancel button.  

loading app and hitting F5 displays the preview
hitting F5 a second time while the preview is displayed gives the error display (see below)
you have to save and reload the wxg file before you can preview again.

This error seems to be specific to this particular wxg file but seems to happen whatever widget is currently displayed.   Object may be found in github johns1c/wxgfiles/Cmail_kp.wxg

You can still edit and save so it does not seem to be of utmost priority.  
  Previously could has started triggering an error in preview

ERROR   : None
An unexpected error occurred!

Exception type:      <class 'TypeError'>
Exception details:   'Button' object is not callable

Application stack traceback:
  File "C:\Python38\lib\site-packages\wx\core.py", line 3383, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "D:\CJWork\Python\wxGlade-master\main.py", line 815, in preview
    toplevel.preview(refresh=True)
  File "D:\CJWork\Python\wxGlade-master\new_properties.py", line 3358, in __call__
    self.callback(*args, **kwargs)
  File "D:\CJWork\Python\wxGlade-master\edit_windows.py", line 784, in on_preview
    self.preview_widget.Close()

Date and time:       2021-06-17T13:51:12.655194
Python version:      3.8.2
wxPython version:    4.1.0
wxWidgets platform:  __WXMSW__
wxGlade version:     1.1.0pre

**Comment by johns1c** [comment] 2021-06-19 09:53
[Cmail_kp.txt](https://github.com/wxGlade/wxGlade/files/6680447/Cmail_kp.txt)
need to rename to wxg as could not upload with that extension

**Comment by johns1c** [comment] 2021-06-19 14:24
Dear Dietmar,

Please find file attached.  

1 Open File
2 Hit F5 to preview
3 Hit F5 a second time  to close and reopen preview --- error displayed

the error occurs on closing the preview and can also be triggered by using the preview button in the 
edit dialog panel

if I add a second dialog to the app I can open / close this one without problem


Chris

----- Original Message -----

**Comment by DietmarSchwertberger** [comment] 2021-06-21 15:34
Thanks a lot. I will look into this to implement a fix.
The problem is caused by naming your button `Close`. This masks the wxPython method `Dialog.Close`.
It's not a good idea to use such names. Better use e.g. `btn_close` or `btnClose`

**Comment by DietmarSchwertberger** [comment] 2021-06-22 18:05
A fix is in the repository master branch. I won't change this for 1.0.x

**Comment by DietmarSchwertberger** [comment] 2023-11-26 14:48
pre-release 1.1.0a1 is online now

**Closed by DietmarSchwertberger** 2023-11-26 14:48 UTC
Labels: bug, pending
